#!/usr/bin/env bash
set -ex

case "$1" in

 jitpack)
   exec $0 mill -j 0 __.publishM2Local
 ;;
 
 mill)
   exec $0 cs launch --scala 2.13.8 mill -- "${@:2}"
 ;;

 mill-i)
   exec $0 cs launch --scala 2.13.8 mill-interactive -- -i "${@:2}"
 ;;

 scalafmt)
   exec $0 cs launch --scala 2.13.8 scalafmt -- --diff "${@:2}"
 ;;

 cs)
   test -x cs || {
     curl -o cs -qL https://git.io/coursier-cli
     chmod +x cs
   }
   exec ./cs "${@:2}"
 ;;

 publishLocal)
  $0 mill-i -j 0 -D PUBLISH_VERSION=latest __.publishLocal
  ;;

 example)
   $0 publishLocal
   (cd example; ../ci mill _.compile)
   grep Generated example/out/hello/scalaxbGeneratedSources.dest/*.scala
   file example/out/hello/compile.dest/classes/example/Request.class
   file example/out/hello/compile.dest/classes/scalaxb/Helper.class
 ;;

 test)
   $0 scalafmt --test
   $0 example
 ;;

 *)
   echo "Command not found ci ${@}"
   exit 1
 ;;

esac
