#!/usr/bin/env bash
set -ex

case "$1" in

 jitpack)
   exec $0 mill _.publishM2Local
 ;;
 
 mill)
   exec $0 cs launch mill -- "${@:2}"
 ;;

 scalafmt)
   exec $0 cs launch scalafmt -- --mode diff --diff-branch master "${@:2}"
 ;;

 cs)
   test -x cs || {
     curl -o cs -qL https://git.io/coursier-cli
     chmod +x cs
   }
   exec ./cs "${@:2}"
 ;;

 test)
   $0 scalafmt --test
   $0 mill _.publishLocal 
   (cd example; ../ci mill _.compile)
   grep Generated example/out/hello/scalaxbGeneratedSources/dest/*.scala
   file example/out/hello/compile/dest/classes/example/Request.class
   file example/out/hello/compile/dest/classes/scalaxb/Helper.class
 ;;

esac
